version: "3.9"

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: product_db
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  product-service:
    image: product-service:dev
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    env_file:
      - ../.env
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DB_URL: jdbc:postgresql://postgres:5432/product_db

volumes:
  postgres_data:
